Separate CXX flags for MSVC and GCC
JethroDevon/revengeMusic pull request #49
Opened 2017-05-23 20:19 UTC by MonJamp

Needs testing on Windows

2017-05-23 20:56 UTC, Dyrand commented
This PR depends on other commits include other commits which are within https://github.com/JethroDevon/revengeMusic/pull/48
Possibly work on separate branches for each related changes you might want to make?

2017-05-23 21:05 UTC, Dyrand requested changes

2017-05-23 21:05 UTC, Dyrand commented on CMakeLists.txt
> +  set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE}")
Equivalent flag for MSVC is probably /O2

2017-05-23 21:05 UTC, Dyrand commented on CMakeLists.txt
> +  set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -W4")
Is that syntax accepted? 
I'm only aware of the flags being accepted with a forward slash: /W4

2017-05-23 21:25 UTC, Dyrand commented
I created a merge commit instead of a rebase for the other PR you made that fixed #44, so I reverted it.
This PR fixes both #42 and #44, so it should be alright?

2017-05-24 03:36 UTC, MonJamp commented on CMakeLists.txt
> +  set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -W4")
Oddly enough `-Wall` and `-W4` do work in MSVC (maybe due to cmake), but I'll change it to the proper format.

2017-05-24 04:10 UTC, Dyrand commented on CMakeLists.txt
> +  set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /Od /W4")
One of these debug flags may be convenient: https://docs.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format

2017-05-24 04:13 UTC, Dyrand approved these changes

2017-05-24 04:14 UTC, merged