Build scripts for Windows that account for both build types
JethroDevon/revengeMusic pull request #58
Opened 2017-05-24 22:11 UTC by Dyrand

Fixes #57 for Windows
I'm not sure this is the way it should be done, but it does work.

2017-05-24 22:16 UTC, MonJamp commented
I forgot we had build scripts. Why not have one script that takes in the build type as an argument? Also what's the point of line 20 in CMakelists.txt?

2017-05-24 22:44 UTC, Dyrand commented
The build types defaults to: "Debug;Release;MinSizeRel;RelWithDebInfo"
So I just limited it to the types we work with.
As for a script that takes the build type as an argument, I just didn't think of it.
I'll change it to a script that takes arguments.

2017-05-25 05:46 UTC, MonJamp requested changes

2017-05-25 05:46 UTC, MonJamp commented on build.cmd
> +mkdir %build_type%
There's no need to separate the CMake generated files. CMake transfers the configurations to VS so you can build both configurations and VS will output them to Debug/ and Release/ receptively. If you change the script up a bit you could run `build Debug & build Release` or via MSBuild `msbuild revengeMusic.sln /p:Configuration=Debug & msbuild revengeMusic.sln /p:Configuration=Release`.

2017-05-25 05:47 UTC, MonJamp commented on build.cmd
> +mkdir %build_type%
Also it would be nice to add return to the directory in which the command was run at.

2017-05-25 17:34 UTC, MonJamp approved these changes

2017-05-25 17:35 UTC, merged